# -*- coding: utf-8 -*-
"""CVIP ASSIGNMENT 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sb2GCGqyLswQeP8Vvi85FNFHemf4dm5x
"""

# Step 1: Install dependencies
!pip install -q ultralytics opencv-python-headless matplotlib

# Step 2: Import libraries
from ultralytics import YOLO
import cv2
import matplotlib.pyplot as plt
from google.colab import files

# Step 3: Upload single image
print("Please upload a single image for object detection:")
uploaded = files.upload()

# Extract uploaded file path (only one image)
image_path = list(uploaded.keys())[0]

# Step 4: Load the largest YOLOv8 model for accuracy
model = YOLO('yolov8x.pt')  # highest accuracy model

# Step 5: Perform detection with high confidence threshold, larger image size, TTA enabled
results = model.predict(
    source=image_path,
    conf=0.6,         # confidence threshold
    iou=0.5,          # IoU threshold for NMS
    imgsz=1024,       # high resolution for accuracy
    augment=True      # test time augmentation for robustness
)

# Step 6: Save and display results
result_img = results[0].plot()

# Save annotated image
output_path = f"annotated_{image_path}"
cv2.imwrite(output_path, result_img)
print(f"Annotated image saved to: {output_path}")

# Show image inline in Colab
plt.figure(figsize=(12, 8))
plt.imshow(cv2.cvtColor(result_img, cv2.COLOR_BGR2RGB))
plt.axis('off')
plt.title("YOLOv8 Object Detection Results")
plt.show()

# Step 7: Print detected objects
print("Detected objects (Class, Confidence, Box coordinates):")
classes = model.names
for box in results[0].boxes:
    class_id = int(box.cls)
    confidence = float(box.conf)
    bbox = [round(coordinate, 2) for coordinate in box.xyxy[0].tolist()]  # [x1,y1,x2,y2]
    print(f"- {classes[class_id]} | Confidence: {confidence:.2f} | Box: {bbox}")

